### ISSUE TITLE
Adapter not defined

### ISSUE THREAD

**Issue by TheJedinator** [tarsiusid/janus-room#47]
Trying to bring this into my project and getting adapter undefined. when I modify it to use the global instance of a WebRTCAdapter I get TypeError: Cannot read property 'browserDetails' of undefined". Any help would be appreciated. I've been sinking several hours into trying to use this and janus-gateway proper with neither working...

**Comment by Qvatra** [comment]
@TheJedinator same problem here, would you mind to share how did you solved it?
